USE [C34_BI];
GO
SET XACT_ABORT ON;
-- OPCIONAL. Ejecutar después de cargar Silver y confirmar la semántica.
-- 34 candidatas compatibles con los datos de 2020; no declaradas por FoxPro.
-- Incluyen LoteId para no mezclar empresas, años ni versiones del origen.
-- Las futuras cargas respetan su orden de dependencias; una infracción revierte Silver.
DECLARE @Aplicar bit=0;
IF @Aplicar=1
BEGIN
BEGIN TRY
BEGIN TRANSACTION;
IF NOT EXISTS(SELECT 1 FROM sys.key_constraints WHERE parent_object_id=OBJECT_ID(N'silver.AFPS') AND name=N'UQ_S_BUS_1')
ALTER TABLE silver.[AFPS] ADD CONSTRAINT [UQ_S_BUS_1] UNIQUE ([_LoteId],[C_AFP]);
IF NOT EXISTS(SELECT 1 FROM sys.key_constraints WHERE parent_object_id=OBJECT_ID(N'silver.ALMACEN') AND name=N'UQ_S_BUS_2')
ALTER TABLE silver.[ALMACEN] ADD CONSTRAINT [UQ_S_BUS_2] UNIQUE ([_LoteId],[C_ALMA]);
IF NOT EXISTS(SELECT 1 FROM sys.key_constraints WHERE parent_object_id=OBJECT_ID(N'silver.BIENES') AND name=N'UQ_S_BUS_3')
ALTER TABLE silver.[BIENES] ADD CONSTRAINT [UQ_S_BUS_3] UNIQUE ([_LoteId],[C_BIEN]);
IF NOT EXISTS(SELECT 1 FROM sys.key_constraints WHERE parent_object_id=OBJECT_ID(N'silver.CTACTE') AND name=N'UQ_S_BUS_4')
ALTER TABLE silver.[CTACTE] ADD CONSTRAINT [UQ_S_BUS_4] UNIQUE ([_LoteId],[N_DEUD]);
IF NOT EXISTS(SELECT 1 FROM sys.key_constraints WHERE parent_object_id=OBJECT_ID(N'silver.MONEDA') AND name=N'UQ_S_BUS_5')
ALTER TABLE silver.[MONEDA] ADD CONSTRAINT [UQ_S_BUS_5] UNIQUE ([_LoteId],[C_MONE]);
IF NOT EXISTS(SELECT 1 FROM sys.key_constraints WHERE parent_object_id=OBJECT_ID(N'silver.OPERACION') AND name=N'UQ_S_BUS_6')
ALTER TABLE silver.[OPERACION] ADD CONSTRAINT [UQ_S_BUS_6] UNIQUE ([_LoteId],[C_OPER]);
IF NOT EXISTS(SELECT 1 FROM sys.key_constraints WHERE parent_object_id=OBJECT_ID(N'silver.PRODUCTO') AND name=N'UQ_S_BUS_7')
ALTER TABLE silver.[PRODUCTO] ADD CONSTRAINT [UQ_S_BUS_7] UNIQUE ([_LoteId],[C_PROD]);
IF NOT EXISTS(SELECT 1 FROM sys.key_constraints WHERE parent_object_id=OBJECT_ID(N'silver.SC_PLAN') AND name=N'UQ_S_BUS_8')
ALTER TABLE silver.[SC_PLAN] ADD CONSTRAINT [UQ_S_BUS_8] UNIQUE ([_LoteId],[C_CUEN]);
IF NOT EXISTS(SELECT 1 FROM sys.key_constraints WHERE parent_object_id=OBJECT_ID(N'silver.SITUACION') AND name=N'UQ_S_BUS_9')
ALTER TABLE silver.[SITUACION] ADD CONSTRAINT [UQ_S_BUS_9] UNIQUE ([_LoteId],[C_SITU]);
IF NOT EXISTS(SELECT 1 FROM sys.key_constraints WHERE parent_object_id=OBJECT_ID(N'silver.TIPCOMPROB') AND name=N'UQ_S_BUS_10')
ALTER TABLE silver.[TIPCOMPROB] ADD CONSTRAINT [UQ_S_BUS_10] UNIQUE ([_LoteId],[C_COMP]);
IF NOT EXISTS(SELECT 1 FROM sys.key_constraints WHERE parent_object_id=OBJECT_ID(N'silver.TIPDCTOS') AND name=N'UQ_S_BUS_11')
ALTER TABLE silver.[TIPDCTOS] ADD CONSTRAINT [UQ_S_BUS_11] UNIQUE ([_LoteId],[C_DOCU]);
IF NOT EXISTS(SELECT 1 FROM sys.key_constraints WHERE parent_object_id=OBJECT_ID(N'silver.TIPEXPROD') AND name=N'UQ_S_BUS_12')
ALTER TABLE silver.[TIPEXPROD] ADD CONSTRAINT [UQ_S_BUS_12] UNIQUE ([_LoteId],[K_EXIS]);
IF NOT EXISTS(SELECT 1 FROM sys.key_constraints WHERE parent_object_id=OBJECT_ID(N'silver.TIPOUNID') AND name=N'UQ_S_BUS_13')
ALTER TABLE silver.[TIPOUNID] ADD CONSTRAINT [UQ_S_BUS_13] UNIQUE ([_LoteId],[K_MEDI]);
IF NOT EXISTS(SELECT 1 FROM sys.key_constraints WHERE parent_object_id=OBJECT_ID(N'silver.VENDEDOR') AND name=N'UQ_S_BUS_14')
ALTER TABLE silver.[VENDEDOR] ADD CONSTRAINT [UQ_S_BUS_14] UNIQUE ([_LoteId],[C_VEND]);
IF NOT EXISTS(SELECT 1 FROM sys.key_constraints WHERE parent_object_id=OBJECT_ID(N'silver.VOUCHER') AND name=N'UQ_S_BUS_15')
ALTER TABLE silver.[VOUCHER] ADD CONSTRAINT [UQ_S_BUS_15] UNIQUE ([_LoteId],[C_AÑO],[C_MES],[C_OPER],[N_OPER]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.DATPERS') AND name=N'FK_S_BUS_1')
ALTER TABLE silver.[DATPERS] WITH CHECK ADD CONSTRAINT [FK_S_BUS_1] FOREIGN KEY ([_LoteId],[C_AFP]) REFERENCES silver.[AFPS] ([_LoteId],[C_AFP]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.IMPOAFPS') AND name=N'FK_S_BUS_2')
ALTER TABLE silver.[IMPOAFPS] WITH CHECK ADD CONSTRAINT [FK_S_BUS_2] FOREIGN KEY ([_LoteId],[C_AFP]) REFERENCES silver.[AFPS] ([_LoteId],[C_AFP]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.SISPROP') AND name=N'FK_S_BUS_3')
ALTER TABLE silver.[SISPROP] WITH CHECK ADD CONSTRAINT [FK_S_BUS_3] FOREIGN KEY ([_LoteId],[C_ALMA]) REFERENCES silver.[ALMACEN] ([_LoteId],[C_ALMA]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.DEPBIEN') AND name=N'FK_S_BUS_4')
ALTER TABLE silver.[DEPBIEN] WITH CHECK ADD CONSTRAINT [FK_S_BUS_4] FOREIGN KEY ([_LoteId],[C_BIEN]) REFERENCES silver.[BIENES] ([_LoteId],[C_BIEN]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.DETCTACTE') AND name=N'FK_S_BUS_5')
ALTER TABLE silver.[DETCTACTE] WITH CHECK ADD CONSTRAINT [FK_S_BUS_5] FOREIGN KEY ([_LoteId],[N_DEUD]) REFERENCES silver.[CTACTE] ([_LoteId],[N_DEUD]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.ASIDEST') AND name=N'FK_S_BUS_6')
ALTER TABLE silver.[ASIDEST] WITH CHECK ADD CONSTRAINT [FK_S_BUS_6] FOREIGN KEY ([_LoteId],[K_MONE]) REFERENCES silver.[MONEDA] ([_LoteId],[C_MONE]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.CTACTE') AND name=N'FK_S_BUS_7')
ALTER TABLE silver.[CTACTE] WITH CHECK ADD CONSTRAINT [FK_S_BUS_7] FOREIGN KEY ([_LoteId],[K_MONE]) REFERENCES silver.[MONEDA] ([_LoteId],[C_MONE]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.DETCTACTE') AND name=N'FK_S_BUS_8')
ALTER TABLE silver.[DETCTACTE] WITH CHECK ADD CONSTRAINT [FK_S_BUS_8] FOREIGN KEY ([_LoteId],[K_MONE]) REFERENCES silver.[MONEDA] ([_LoteId],[C_MONE]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.DET_VOUCH') AND name=N'FK_S_BUS_9')
ALTER TABLE silver.[DET_VOUCH] WITH CHECK ADD CONSTRAINT [FK_S_BUS_9] FOREIGN KEY ([_LoteId],[K_MONE]) REFERENCES silver.[MONEDA] ([_LoteId],[C_MONE]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.SISPROP') AND name=N'FK_S_BUS_10')
ALTER TABLE silver.[SISPROP] WITH CHECK ADD CONSTRAINT [FK_S_BUS_10] FOREIGN KEY ([_LoteId],[K_MONE]) REFERENCES silver.[MONEDA] ([_LoteId],[C_MONE]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.ASIDEST') AND name=N'FK_S_BUS_11')
ALTER TABLE silver.[ASIDEST] WITH CHECK ADD CONSTRAINT [FK_S_BUS_11] FOREIGN KEY ([_LoteId],[C_OPER]) REFERENCES silver.[OPERACION] ([_LoteId],[C_OPER]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.CTACTE') AND name=N'FK_S_BUS_12')
ALTER TABLE silver.[CTACTE] WITH CHECK ADD CONSTRAINT [FK_S_BUS_12] FOREIGN KEY ([_LoteId],[C_OPER]) REFERENCES silver.[OPERACION] ([_LoteId],[C_OPER]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.DETCTACTE') AND name=N'FK_S_BUS_13')
ALTER TABLE silver.[DETCTACTE] WITH CHECK ADD CONSTRAINT [FK_S_BUS_13] FOREIGN KEY ([_LoteId],[C_OPER]) REFERENCES silver.[OPERACION] ([_LoteId],[C_OPER]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.DET_VOUCH') AND name=N'FK_S_BUS_14')
ALTER TABLE silver.[DET_VOUCH] WITH CHECK ADD CONSTRAINT [FK_S_BUS_14] FOREIGN KEY ([_LoteId],[C_OPER]) REFERENCES silver.[OPERACION] ([_LoteId],[C_OPER]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.VOUCHER') AND name=N'FK_S_BUS_15')
ALTER TABLE silver.[VOUCHER] WITH CHECK ADD CONSTRAINT [FK_S_BUS_15] FOREIGN KEY ([_LoteId],[C_OPER]) REFERENCES silver.[OPERACION] ([_LoteId],[C_OPER]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.MEDIPROD') AND name=N'FK_S_BUS_16')
ALTER TABLE silver.[MEDIPROD] WITH CHECK ADD CONSTRAINT [FK_S_BUS_16] FOREIGN KEY ([_LoteId],[C_PROD]) REFERENCES silver.[PRODUCTO] ([_LoteId],[C_PROD]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.ASIDEST') AND name=N'FK_S_BUS_17')
ALTER TABLE silver.[ASIDEST] WITH CHECK ADD CONSTRAINT [FK_S_BUS_17] FOREIGN KEY ([_LoteId],[C_CUEN]) REFERENCES silver.[SC_PLAN] ([_LoteId],[C_CUEN]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.CTACTE') AND name=N'FK_S_BUS_18')
ALTER TABLE silver.[CTACTE] WITH CHECK ADD CONSTRAINT [FK_S_BUS_18] FOREIGN KEY ([_LoteId],[C_CUEN]) REFERENCES silver.[SC_PLAN] ([_LoteId],[C_CUEN]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.DET_VOUCH') AND name=N'FK_S_BUS_19')
ALTER TABLE silver.[DET_VOUCH] WITH CHECK ADD CONSTRAINT [FK_S_BUS_19] FOREIGN KEY ([_LoteId],[C_CUEN]) REFERENCES silver.[SC_PLAN] ([_LoteId],[C_CUEN]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.PRODUCTO') AND name=N'FK_S_BUS_20')
ALTER TABLE silver.[PRODUCTO] WITH CHECK ADD CONSTRAINT [FK_S_BUS_20] FOREIGN KEY ([_LoteId],[C_CTAC]) REFERENCES silver.[SC_PLAN] ([_LoteId],[C_CUEN]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.PRODUCTO') AND name=N'FK_S_BUS_21')
ALTER TABLE silver.[PRODUCTO] WITH CHECK ADD CONSTRAINT [FK_S_BUS_21] FOREIGN KEY ([_LoteId],[C_CTAV]) REFERENCES silver.[SC_PLAN] ([_LoteId],[C_CUEN]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.SISPROP') AND name=N'FK_S_BUS_22')
ALTER TABLE silver.[SISPROP] WITH CHECK ADD CONSTRAINT [FK_S_BUS_22] FOREIGN KEY ([_LoteId],[C_CUEN]) REFERENCES silver.[SC_PLAN] ([_LoteId],[C_CUEN]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.DATPERS') AND name=N'FK_S_BUS_23')
ALTER TABLE silver.[DATPERS] WITH CHECK ADD CONSTRAINT [FK_S_BUS_23] FOREIGN KEY ([_LoteId],[C_SITU]) REFERENCES silver.[SITUACION] ([_LoteId],[C_SITU]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.CTACTE') AND name=N'FK_S_BUS_24')
ALTER TABLE silver.[CTACTE] WITH CHECK ADD CONSTRAINT [FK_S_BUS_24] FOREIGN KEY ([_LoteId],[C_COMP]) REFERENCES silver.[TIPCOMPROB] ([_LoteId],[C_COMP]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.SISPROP') AND name=N'FK_S_BUS_25')
ALTER TABLE silver.[SISPROP] WITH CHECK ADD CONSTRAINT [FK_S_BUS_25] FOREIGN KEY ([_LoteId],[C_COMP]) REFERENCES silver.[TIPCOMPROB] ([_LoteId],[C_COMP]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.CTACTE') AND name=N'FK_S_BUS_26')
ALTER TABLE silver.[CTACTE] WITH CHECK ADD CONSTRAINT [FK_S_BUS_26] FOREIGN KEY ([_LoteId],[C_DOCU]) REFERENCES silver.[TIPDCTOS] ([_LoteId],[C_DOCU]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.DATPERS') AND name=N'FK_S_BUS_27')
ALTER TABLE silver.[DATPERS] WITH CHECK ADD CONSTRAINT [FK_S_BUS_27] FOREIGN KEY ([_LoteId],[C_DOCU]) REFERENCES silver.[TIPDCTOS] ([_LoteId],[C_DOCU]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.VENDEDOR') AND name=N'FK_S_BUS_28')
ALTER TABLE silver.[VENDEDOR] WITH CHECK ADD CONSTRAINT [FK_S_BUS_28] FOREIGN KEY ([_LoteId],[C_DOCU]) REFERENCES silver.[TIPDCTOS] ([_LoteId],[C_DOCU]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.PRODUCTO') AND name=N'FK_S_BUS_29')
ALTER TABLE silver.[PRODUCTO] WITH CHECK ADD CONSTRAINT [FK_S_BUS_29] FOREIGN KEY ([_LoteId],[K_EXIS]) REFERENCES silver.[TIPEXPROD] ([_LoteId],[K_EXIS]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.MEDIPROD') AND name=N'FK_S_BUS_30')
ALTER TABLE silver.[MEDIPROD] WITH CHECK ADD CONSTRAINT [FK_S_BUS_30] FOREIGN KEY ([_LoteId],[K_MEDI]) REFERENCES silver.[TIPOUNID] ([_LoteId],[K_MEDI]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.SISPROP') AND name=N'FK_S_BUS_31')
ALTER TABLE silver.[SISPROP] WITH CHECK ADD CONSTRAINT [FK_S_BUS_31] FOREIGN KEY ([_LoteId],[C_VEND]) REFERENCES silver.[VENDEDOR] ([_LoteId],[C_VEND]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.ASIDEST') AND name=N'FK_S_BUS_32')
ALTER TABLE silver.[ASIDEST] WITH CHECK ADD CONSTRAINT [FK_S_BUS_32] FOREIGN KEY ([_LoteId],[C_AÑO],[C_MES],[C_OPER],[N_OPER]) REFERENCES silver.[VOUCHER] ([_LoteId],[C_AÑO],[C_MES],[C_OPER],[N_OPER]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.CTACTE') AND name=N'FK_S_BUS_33')
ALTER TABLE silver.[CTACTE] WITH CHECK ADD CONSTRAINT [FK_S_BUS_33] FOREIGN KEY ([_LoteId],[C_AÑO],[C_MES],[C_OPER],[N_OPER]) REFERENCES silver.[VOUCHER] ([_LoteId],[C_AÑO],[C_MES],[C_OPER],[N_OPER]);
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE parent_object_id=OBJECT_ID(N'silver.DET_VOUCH') AND name=N'FK_S_BUS_34')
ALTER TABLE silver.[DET_VOUCH] WITH CHECK ADD CONSTRAINT [FK_S_BUS_34] FOREIGN KEY ([_LoteId],[C_AÑO],[C_MES],[C_OPER],[N_OPER]) REFERENCES silver.[VOUCHER] ([_LoteId],[C_AÑO],[C_MES],[C_OPER],[N_OPER]);
COMMIT;
END TRY
BEGIN CATCH
IF @@TRANCOUNT>0 ROLLBACK;
THROW;
END CATCH;
END;
GO
